### ISSUE TITLE
Add Icons to Menus and on the functions tree

### ISSUE THREAD

**Issue by hexaredecimal** [hexaredecimal/EquCyph#3]

**Comment by seherkrgz** [comment]
Which programming language?

**Comment by hexaredecimal** [comment]
Java, wanna help?

**Comment by seherkrgz** [comment]
Sorry, I have no experience with Java

**Comment by anehemya** [comment]
Hey hexaredecimal! I would like to help

**Comment by hexaredecimal** [comment]
Yay!! Welcome to the project , fork it, make changes then submit Pull Requests. The icons were pushed in this commit: 3bf631ec542062c9a051048f8a4a24f49cdfe92c. Lets try and get them to work on the menu and the functions tree.

**Comment by hexaredecimal** [comment]
Icons have now been implemented into the project. Closing this issue.
